Декоративные элементы на внутренней странице
htmlacademy-htmlcss/83102-sedona-32 pull request #10
Opened 2021-11-13 10:31 UTC by aksv

Декоративные элементы на внутренней странице + правки по ревью

2021-11-13 18:38 UTC, Viktor-Rybakov requested changes
Нужно добавить стили для разных состояний:
`btn-apply`, `btn-reset`

Не забудь про добавление фавиконки: https://up.htmlacademy.ru/htmlcss/32/book/2.4

2021-11-13 18:38 UTC, Viktor-Rybakov commented on css/styles.css
> +.total-items-form {
Нужно добавить выравнивание и стрелку
![изображение](https://user-images.githubusercontent.com/53224541/141654832-b8254de7-d5ad-48bb-a0a1-efe64c854373.png)

2021-11-13 18:38 UTC, Viktor-Rybakov commented on index.html
> +      <div class="contacts">
Здесь мне кажется нелогичным распределение отступов слева и справа.

![изображение](https://user-images.githubusercontent.com/53224541/141654911-347e2193-d911-41af-9535-e0cbc5bc9965.png)
![изображение](https://user-images.githubusercontent.com/53224541/141654954-92c33ef1-aa59-4080-ae07-e3b1331d465f.png)

2021-11-13 18:38 UTC, Viktor-Rybakov commented on index.html
>          <div class="phone-link-container">
Этот контейнер не избыточен, как и `htmlacademy-link-container` ?
У тебя ссылки сделаны блочными, и для них можно указать внешние отсупы

2021-11-13 18:38 UTC, Viktor-Rybakov commented on css/styles.css
>  .contacts {
Чтобы здесь были логичные отступы, и не было лишних контейнеров, попробуй задать паддинг слева и справа.
Чтобы выровнять телефон по центру, попробуй поиграться с гридом: можно настроить колонки таким образом: `grid-template-colums: 1fr max-content 1fr`

2021-11-15 18:10 UTC, Viktor-Rybakov requested changes

2021-11-15 18:10 UTC, Viktor-Rybakov commented on index.html
> +                <span class="passengers-decrement-icon"></span>
Это дополнительный элемент в разметке, можно его сделать всевдоэлементом

2021-11-15 18:10 UTC, Viktor-Rybakov commented on index.html
> +              <div class="help-triangle"></div>
Этот хвостик лучше сделать псевдоэлементом control-help

2021-11-15 18:10 UTC, Viktor-Rybakov commented on index.html
> +                    <span class="hotel-preview-name">Desert Quail Inn</span>
Это можно сделать заголовком

2021-11-15 18:10 UTC, Viktor-Rybakov commented on index.html
> +          <div class="popover popover-favorites">
Для такого всплывающего окна можно добавить семантики и использовать либо section либо aside, мне кажется второе ближе по смыслу, потому что это у нас что-то дополнительное.
Тогда для поповера можно добавить скрытый заголовок

2021-11-15 18:10 UTC, Viktor-Rybakov commented on index.html
> +                    <img class="hotel-preview-img" src="./img/hotels/hotel-2-preview.png" width="48">
не забыть alt

2021-11-15 18:10 UTC, Viktor-Rybakov commented on css/styles.css
> +  border: 1px solid var(--basic-gray);
Чтобы у кнопки не было такого бордера, кнопке можно добавить отрицательный марджин 
![изображение](https://user-images.githubusercontent.com/53224541/141832576-9f33302f-cbad-45e2-aff7-16f826e7abdf.png)

2021-11-16 22:06 UTC, Viktor-Rybakov requested changes
Нужно проставить ссылки на соцсети (требования из макета):
Facebook — https://www.facebook.com/htmlacademy
Twitter — https://twitter.com/htmlacademy_ru
Youtube — https://www.youtube.com/c/HTMLAcademyRUS

### Замечания по код-стайлу:

- заменить в CSS кавычки [на двойные](http://codeguide.academy/html-css.html#css-quotes)

- Правильно оформить  [перенос селекторов](http://codeguide.academy/html-css.html#css-multiselectors)

- Поставить атрибут `class`  [в начало](http://codeguide.academy/html-css.html#html-attr-order) - такое много где по коду есть.

### Замечания по критериям:

- добавить в конце описания изображений точки [ALLY-01. Описание графики](https://up.htmlacademy.ru/htmlcss/32/criteries#ALLY-01)

- Для `.catalog-search` `.sedona-welcome` `.subscription` добавить контрастный цвет фона на случай, если картинка не загрузится [ALLY-05. Фоновый цвет у фоновых картинок. ](https://up.htmlacademy.ru/htmlcss/32/criteries#ALLY-05)

- У тебя есть глобальный селектор (по тегу) `button`, эти стили нужно использовать с классом [CSS-02. Глобальный селектор](https://up.htmlacademy.ru/htmlcss/32/criteries#CSS-02)

А вот для `img` можно добавить глобавльные свойства: `max-width: 100%`, `height: auto`, `object-fit: contain`

### Переполнение.
в некоторых местах, например тут, текст не ограничен по ширине и при разных стечениях обстоятельств он может некрасиво прилипнуть к краю. В таком случае можно тексту задать максимальную ширину (с небольшим запасом, потому что в разных браузерах шрифты рендерятся по-разному) и при необходимости этот блок центрировать, например, с помощью марджинов.
![изображение](https://user-images.githubusercontent.com/53224541/142071179-4744cb1d-59df-4437-92f2-344be878de31.png)
У тебя часто в разметке встречается перенос строк с помощью тега br, это допустимо, но лучше такие переносы (а точнее длину строк) формировать с помощью ширины блоков. Ведь когда-нибудь потом контент может наполняться из CMS и контент-менеджер вряд ли будет расставлять переносы)

При переполнении фон в блоках должен тянуться, например, в `.subscription`, решается с помощью background-size: cover;

В форме переполнение ломает сетку
![изображение](https://user-images.githubusercontent.com/53224541/142072440-fe3076e3-2a27-484d-b826-930652592ec3.png)
У тебя работает всё как надо - контент не пропадает, блоки переносятся на новую строку, но такое переполнение можно обыграть лучше: убрать у .filter-form flex-wrap: wrap; Тогда fieldsetы не будут переносиься, а будет переноситься текст.
![изображение](https://user-images.githubusercontent.com/53224541/142072775-3adbde74-6c7a-4f73-b9c7-47e5018db47c.png)
Только нужно .control-mark задать flex-shrink: 0; чтобы его не сплющивало.

Либо второй вариант - задать максимамльную ширину для fieldset и оставить у .filter-form flex-wrap: wrap

И внизу секции я рекомендую задать паддинг, чтобы было красиво :)
![изображение](https://user-images.githubusercontent.com/53224541/142073035-1718f58b-9bb4-459a-92f4-190dbd23b9a3.png)

Переполнение пагинатора сломало страницу, нужно задать его макс ширину и flex-wrap
![изображение](https://user-images.githubusercontent.com/53224541/142073402-fc902732-749f-4264-9d90-1fc4dffb65eb.png)

2021-11-17 17:59 UTC, aksv commented on css/styles.css
> +  width: 14px;
По стайлгайду больше, а при наложением pixel perfect меньше

2021-11-17 17:59 UTC, aksv commented on css/styles.css
> +  padding: 12px 20px 12px 16px;
те которые по 12? Будет тогда 3, а не один

2021-11-17 18:04 UTC, aksv commented on index.html
> +              <div class="control-help">
я не знаю, пока для себя понял - если хотят переносы как на макете, считаю текст декоративным и ставлю <br>, если нужны общие параметры текста что бы совпадали, но не перенос в перенос, тогда без br.
Если подгонять ширину под перенос получается слишком ломко, по крайней мере с моим уровнем. Я бы не рисковал

2021-11-17 18:06 UTC, aksv commented on css/styles.css
> +  right: -112px;
сделал процентами, но все равно выглядит как костыль. Нужно изначально было планировать компонент с прицелом на то что у него будет абсолютно позиционированный child, но я бы не стал уже сейчас переделывать.

2021-11-17 18:23 UTC, Viktor-Rybakov commented on catalog.html
> +                    <input class="price-min number-input" type="number" name="price-min" id="price-min" placeholder="0">
Нет, в одном 0, в другом 9000.

2021-11-17 18:27 UTC, Viktor-Rybakov commented on css/styles.css
> +  padding: 12px 20px 12px 16px;
В такой записи `padding-top` и `padding-bottom` избыточны - потому что свойство `padding` - составное, в нем задаются несколько значений. Если значений 4, то они идут в следующем порядке: top, right, bottom, left (начиная сверху и по часовой стрелке). Получается  `padding-top` и `padding-bottom` ты уже задал в `padding`
![изображение](https://user-images.githubusercontent.com/53224541/142259894-cba38d2d-5351-4c33-b692-f66916f505aa.png)

2021-11-17 18:27 UTC, Viktor-Rybakov commented on css/styles.css
> +  padding: 12px 20px 12px 16px;
Я не совсем корректно сформулировал замечание, извини :)

2021-11-17 18:39 UTC, Viktor-Rybakov commented
Попробуй спозиционировать модальные окна `.popover` и `.control-help` вот так (мне кажется, что так более понятно - ты явно указываешь, на сколько пикселей сдвинуть вниз, а 50% - выравниевание по центру)

Вот тут описание как это работает, с картинкой: https://medium.com/front-end-weekly/absolute-centering-in-css-ea3a9d0ad72e

![изображение](https://user-images.githubusercontent.com/53224541/142261280-cadee09c-314b-43ab-b6d4-8ea13166ccf6.png)

2021-11-17 22:03 UTC, merged