Разметка главной страницы
htmlacademy-htmlcss/83102-sedona-32 pull request #2
Opened 2021-09-29 08:58 UTC by aksv

2021-09-29 19:00 UTC, Viktor-Rybakov requested changes
Привет! Классная разметка! Замечания и предложения указал в комментариях.
У некоторых тегов ты не используешь классы, потом обрати внимание, что есть критерий на уровень вложенности селекторов (не более двух)

2021-09-30 21:35 UTC, aksv commented on index.html
> +        <h2>Седона — небольшой городок в Аризоне, заслуживающий большего!</h2>
Поменял

2021-09-30 21:36 UTC, aksv commented on index.html
> +          <li class="advantage-item">
Да, это я пропустил, добавил <img>

2021-09-30 21:37 UTC, aksv commented on index.html
> +          <input type="email" name="subcription-emai" />
сделал

2021-10-01 19:09 UTC, Viktor-Rybakov approved these changes

2021-10-01 19:09 UTC, Viktor-Rybakov commented on catalog.html
> +              <button class="visiually-hidden">Показать</button>
У кнопки нужно указать тип, см критерий https://up.htmlacademy.ru/htmlcss/32/criteries#HTML-03

2021-10-01 19:09 UTC, Viktor-Rybakov commented on catalog.html
> +              <button class="view-tile">
У кнопок нужно указать тип, см критерий https://up.htmlacademy.ru/htmlcss/32/criteries#HTML-03

2021-10-01 19:09 UTC, Viktor-Rybakov commented on index.html
> +      </nav>
Здесь мы с тобой пропустили логотип. Обычно логотип делается ссылкой на главную страницу (но на самой главной ссылкой не является)
Чтобы разметка была универсальная, в теге <a> можно удалить атрибут href, тогда он перестанет быть ссылкой. Подробнее про такой прием можно почитать в учебнике https://up.htmlacademy.ru/htmlcss/32/book/1.12

2021-10-01 19:10 UTC, merged