Декоративные элементы на главной странице
htmlacademy-htmlcss/83102-sedona-32 pull request #9
Opened 2021-11-07 18:26 UTC by aksv

2021-11-08 21:46 UTC, Viktor-Rybakov requested changes
Небольшие замечания, из которых главное - если есть необходимость менять цвет иконок, то их нужно размещать в разметке (в реальной практике они собираются в svg-спрайт например) - это касается иконок в соцсетях и логотипе академии.

И про бордеры в кнопках (ты спрашивал в телеге). Я не совсем понял задачу, видимо.
Чтобы сделать обводки для состояния фокуса обычно используют outline - его использовать удобнее, чем border, потому что он не влияет на ширину элемента (в отличии от border). Но есть некоторые кейсы, где нужно менять цвет border, например такой:
![изображение](https://user-images.githubusercontent.com/53224541/140822549-035b212c-720f-4c5a-8801-8a0fae2ba85b.png)

Здесь у синей кнопки при наведении и нажатии есть коричневый border, и высота кнопки вместе с border такая же, как у кнопки в обычном состоянии.
Такой же эффект можно добиться если сделать вместо border  outline с отрицательным отступом outline-offset на ширину рамки

2021-11-08 21:46 UTC, Viktor-Rybakov commented on css/styles.css
>  :root {
См критерий [Формат цветов](http://codeguide.academy/html-css.html#css-color-format) - `Для записи использованы строчные буквы`

2021-11-08 21:46 UTC, Viktor-Rybakov commented on css/styles.css
>  button {
Ты используешь глобальные селекторы для тегов `button`, `ul`, `ol`, `li` - противоречит критерию [CSS-02. Глобальный селектор.](https://up.htmlacademy.ru/htmlcss/32/criteries#CSS-02)

2021-11-08 21:46 UTC, Viktor-Rybakov commented on css/styles.css
> +  left: 23px;
тут логичнее позиционировать от правого края, на мой взгляд

2021-11-08 21:46 UTC, Viktor-Rybakov commented on css/styles.css
> +  background-image: url('../img/svg/social-twitter-dark.svg');
Если есть необходимость менять цвет иконок, то их лучше сделать в разметке (сейчас, на первом уровне). В таком случае темную иконку браузер начнет скачивать только тогда, когда пользователь наведет мышку на иконку. Если что-то случится с интернетом, то иконка не загрузится и не покажется.

2021-11-09 18:39 UTC, aksv commented on css/styles.css
>  button {
поправлю вместе со страницей каталога

2021-11-11 18:45 UTC, Viktor-Rybakov approved these changes
Есть мелкие замечания, присылай их в следующем ДЗ

2021-11-11 18:45 UTC, Viktor-Rybakov commented on index.html
> +                <li class="recommendation-item recommendation-item-hotels">
В хроме и FF  шрифты рендерятся немного по-разному, и этого оказалось достаточно, чтобы заголовок не поместился в отведенные ему 171 пиксель.
Chrome: 
![изображение](https://user-images.githubusercontent.com/53224541/141349977-a22b6e8b-273b-4f3b-bd30-2c4e01640fb5.png)
FF: 
![изображение](https://user-images.githubusercontent.com/53224541/141350016-fca34281-62c7-4c5a-a060-d40b9d0739ef.png)

И обрати внимание, что в FF картинка не растянулась вслед за соседним блоком. Можно поправить, чтобы хорошо отрабатывало переполнение контента. (Попробуй поставить высоту картинки auto)

Посмотри ещё интересное свойсто `object-fit`, может быть его тут можно использовать: https://doka.guide/css/object-fit/

2021-11-11 18:45 UTC, Viktor-Rybakov commented on index.html
> +              <svg class="social-icon" width="20" height="16" viewBox="0 0 20 16" xmlns="http://www.w3.org/2000/svg">
С этой иконкой что-то не так, она как-то коряво отображается (может быть какие-то ошибки при экспорте).
Попробуй удалить лишние элементы - так отображается корректно. У твиттера та же история
![изображение](https://user-images.githubusercontent.com/53224541/141351722-252c2e85-1cdc-43c8-a18c-4a06b69f173d.png)

2021-11-11 18:45 UTC, Viktor-Rybakov commented on index.html
> +              <svg class="social-icon" width="20" height="16" viewBox="0 0 20 16" xmlns="http://www.w3.org/2000/svg">
По идее все иконки довольно простые, и код в svg тоже не должен быть замысловатый

2021-11-11 18:45 UTC, Viktor-Rybakov commented on css/styles.css
> +  background-repeat: no-repeat;
Бекграунд здесь уже не нужен - мы вставили иконки в разметку

2021-11-11 18:45 UTC, merged